# Verwenden Sie ein Basisimage mit PostgreSQL
FROM postgres:latest

# Setzen Sie Umgebungsvariablen
ENV POSTGRES_USER=youruser
ENV POSTGRES_PASSWORD=yourpassword
ENV POSTGRES_DB=yourdatabase

# Öffnen Sie den PostgreSQL-Port
EXPOSE 5432
